name: E2E Tests

on:
  push:
    branches: [ main, master, develop, lutfi-test ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, pdo_mysql
        coverage: none

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Copy .env
      run: cp .env.example .env

    - name: Update .env for CI
      run: |
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel_testing/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env
        echo "APP_URL=http://localhost:8000" >> .env

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Install NPM Dependencies
      run: npm ci

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Build Frontend Assets
      run: npm run build

    - name: Run Database Migrations
      run: php artisan migrate --force

    - name: Seed Database
      run: php artisan db:seed --force

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Start Laravel Server
      run: |
        php artisan serve --no-reload &
        sleep 5

    - name: Wait for server
      run: |
        timeout 30 bash -c 'until curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep -q "200\|302"; do sleep 1; done'

    - name: Run Playwright Tests
      run: npx playwright test --project=chromium
      env:
        CI: true

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30